# Generated by Django 5.0 on 2025-12-08 14:05

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='1234567890123', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
