# Generated by Django 5.0 on 2025-12-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_book_options_book_ordered_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='Name')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Request Date')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='example.book')),
            ],
            options={
                'verbose_name': 'Book Request',
                'verbose_name_plural': 'Book Requests',
                'ordering': ['priority', 'request_date'],
            },
        ),
    ]
