# Generated by Django 5.0 on 2025-12-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_bookrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['request_date'], 'verbose_name': 'Book Request', 'verbose_name_plural': 'Book Requests'},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='priority',
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='example.bookrequest')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
