# Generated by Django 5.0 on 2025-12-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_alter_bookrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='example.bookrequest')),
            ],
            options={
                'verbose_name': 'Request Comment',
                'verbose_name_plural': 'Request Comments',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ActionItem',
        ),
    ]
