# Generated by Django 5.0 on 2025-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_requestcomment_delete_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
    ]
